<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductBundle;

class ProductBundleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeder creates sample product bundles.
     * Will NOT run in production environment for safety.
     */
    public function run(): void
    {
        // Prevent running in production
        if (app()->environment('production')) {
            $this->command->warn('⚠️  ProductBundleSeeder skipped: Cannot run in production environment!');
            return;
        }

        $this->command->info('🌱 Seeding product bundles...');

        $products = Product::active()->get();

        if ($products->count() < 6) {
            $this->command->warn('Need at least 6 products to create bundles. Please create more products first.');
            return;
        }

        $bundles = [
            [
                'name' => 'Complete Writing Set',
                'description' => 'Everything you need for writing - pens, pencils, erasers, and more!',
                'bundle_price' => 29.99,
                'discount_percentage' => 15,
            ],
            [
                'name' => 'School Starter Pack',
                'description' => 'Perfect bundle for students starting a new school year.',
                'bundle_price' => 49.99,
                'discount_percentage' => 20,
            ],
            [
                'name' => 'Office Essentials Bundle',
                'description' => 'All the essential office supplies in one convenient bundle.',
                'bundle_price' => 79.99,
                'discount_percentage' => 10,
            ],
        ];

        foreach ($bundles as $bundleData) {
            // Check if bundle with same name already exists
            $existingBundle = ProductBundle::where('name', $bundleData['name'])->first();
            if ($existingBundle) {
                $this->command->info("Bundle '{$bundleData['name']}' already exists. Skipping...");
                continue;
            }

            // UUID and slug are automatically generated by ProductBundle model boot() method
            $bundle = ProductBundle::create([
                'name' => $bundleData['name'],
                'description' => $bundleData['description'],
                'bundle_price' => $bundleData['bundle_price'],
                'discount_percentage' => $bundleData['discount_percentage'],
                'status' => true,
                'sort_order' => 0,
            ]);

            // Attach 3-4 random products to each bundle using sync to prevent duplicates
            $selectedProducts = $products->random(rand(3, 4));
            $productsData = [];
            foreach ($selectedProducts as $product) {
                $productsData[$product->id] = ['quantity' => rand(1, 3)];
            }
            $bundle->products()->sync($productsData);

            // Recalculate discount percentage based on actual product prices
            $totalProductsPrice = 0;
            foreach ($bundle->products as $product) {
                $totalProductsPrice += ($product->discount_price ?? $product->total_price) * ($product->pivot->quantity ?? 1);
            }

            $discountPercentage = 0;
            if ($totalProductsPrice > 0 && $bundle->bundle_price < $totalProductsPrice) {
                $discountPercentage = (($totalProductsPrice - $bundle->bundle_price) / $totalProductsPrice) * 100;
            }
            $bundle->update(['discount_percentage' => $discountPercentage]);
        }

        $this->command->info("✅ Product Bundles seeded successfully!");
        $this->command->info("  • Processed: " . count($bundles) . " bundles");
    }
}
