<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductFaq;

class ProductFaqSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeder creates sample FAQs for products.
     * Will NOT run in production environment for safety.
     */
    public function run(): void
    {
        // Prevent running in production
        if (app()->environment('production')) {
            $this->command->warn('⚠️  ProductFaqSeeder skipped: Cannot run in production environment!');
            return;
        }

        $this->command->info('🌱 Seeding product FAQs...');

        $products = Product::active()->take(10)->get();

        if ($products->isEmpty()) {
            $this->command->warn('No active products found. Please create products first.');
            return;
        }

        $faqs = [
            [
                'question' => 'What is the size of this product?',
                'answer' => 'The product dimensions are clearly listed in the product description. Please check the specifications section for detailed measurements.',
            ],
            [
                'question' => 'Is this product suitable for children?',
                'answer' => 'Yes, this product is safe for children to use. However, we recommend adult supervision for younger children.',
            ],
            [
                'question' => 'What materials is this product made from?',
                'answer' => 'This product is made from high-quality, eco-friendly materials. Detailed material information is available in the product description.',
            ],
            [
                'question' => 'Can I return this product if I am not satisfied?',
                'answer' => 'Yes, we offer a 30-day return policy. Please keep your receipt and ensure the product is in its original packaging.',
            ],
            [
                'question' => 'How long does shipping take?',
                'answer' => 'Standard shipping within New Zealand takes 3-5 business days. Express shipping options are also available at checkout.',
            ],
            [
                'question' => 'Is this product available in different colors?',
                'answer' => 'Color options vary by product. Please check the product page for available color variations.',
            ],
        ];

        foreach ($products as $product) {
            // Check if ProductFaq already exists for this product
            $existingFaq = ProductFaq::where('product_id', $product->id)->first();
            
            if ($existingFaq) {
                $this->command->info("Product FAQ already exists for product ID: {$product->id}. Skipping...");
                continue;
            }

            // Select 2-3 random FAQs for this product
            $selectedFaqs = collect($faqs)->random(rand(2, 3))->values();
            
            // Build FAQs array in the new JSON format
            $faqsArray = [];
            foreach ($selectedFaqs as $index => $faq) {
                $faqsArray[] = [
                    'question' => $faq['question'],
                    'answer' => $faq['answer'],
                    'sort_order' => $index + 1,
                    'status' => true,
                ];
            }

            // UUID is automatically generated by ProductFaq model boot() method
            ProductFaq::create([
                'product_id' => $product->id,
                'category_id' => $product->category_id, // Get category_id from product
                'faqs' => $faqsArray, // Store all FAQs in JSON format
            ]);
        }

        $this->command->info("✅ Product FAQs seeded successfully!");
        $this->command->info("  • Processed: {$products->count()} products");
    }
}
